// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpULFaiP-jvKhfc2HrwKFI0frrkimCoa0',
    appId: '1:1004752253194:web:e4a252bd3da747c68d8af3',
    messagingSenderId: '1004752253194',
    projectId: 'saferoad-2ef0d',
    authDomain: 'saferoad-2ef0d.firebaseapp.com',
    databaseURL: 'https://saferoad-2ef0d-default-rtdb.firebaseio.com',
    storageBucket: 'saferoad-2ef0d.appspot.com',
    measurementId: 'G-221HPX503Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3y-bGqllr7k3udyuAv9xU4EJTvR4ROBo',
    appId: '1:1004752253194:android:bef3e2f9b502e6138d8af3',
    messagingSenderId: '1004752253194',
    projectId: 'saferoad-2ef0d',
    databaseURL: 'https://saferoad-2ef0d-default-rtdb.firebaseio.com',
    storageBucket: 'saferoad-2ef0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJiIPgzO6kxknbOuLhTt288bhg70VXQLI',
    appId: '1:1004752253194:ios:58dab44bb3e7a9b78d8af3',
    messagingSenderId: '1004752253194',
    projectId: 'saferoad-2ef0d',
    databaseURL: 'https://saferoad-2ef0d-default-rtdb.firebaseio.com',
    storageBucket: 'saferoad-2ef0d.appspot.com',
    androidClientId:
        '1004752253194-fndmnjds0tg5ii71vr91o1bdvtfpel05.apps.googleusercontent.com',
    iosClientId:
        '1004752253194-meptnelkrbm2uj32gjrhbsn7apnt55r2.apps.googleusercontent.com',
    iosBundleId: 'com.example.saferoad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJiIPgzO6kxknbOuLhTt288bhg70VXQLI',
    appId: '1:1004752253194:ios:58dab44bb3e7a9b78d8af3',
    messagingSenderId: '1004752253194',
    projectId: 'saferoad-2ef0d',
    databaseURL: 'https://saferoad-2ef0d-default-rtdb.firebaseio.com',
    storageBucket: 'saferoad-2ef0d.appspot.com',
    androidClientId:
        '1004752253194-fndmnjds0tg5ii71vr91o1bdvtfpel05.apps.googleusercontent.com',
    iosClientId:
        '1004752253194-meptnelkrbm2uj32gjrhbsn7apnt55r2.apps.googleusercontent.com',
    iosBundleId: 'com.example.saferoad',
  );
}
